language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - pip install codecov
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - chmod 777 ./tests/lint_py.sh
# command to run tests
script: ./tests/lint_py.sh
after_success:
  - codecov
